config/routes.rb
Rails.application.routes.draw do
  get 'sessions/create'

  root "home#index"

  namespace :api, defaults: {format: :json} do
    resources :artists, only: [:show, :create, :destroy], module: "artists", param: :name
    resources :location, only: [:create, :update], module: "location"
  end

  namespace :users, path: ":user_name", as: :user do
    get "/dashboard", action: "show", as: :dashboard
    get "/artists", to: "artists#index", as: :artists
    get "/shows", to: "shows#index", as: :shows
  end

  get "/auth/spotify", as: :spotify_login
  get "/auth/spotify/callback", to: "sessions#create"
  delete "/logout",             to: "sessions#destroy"
end

app/views/shared/_navbar.html.erb
<div class="navbar navbar-default navbar-fat navbar-clean">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="icon-bar b1"></span>
        <span class="icon-bar b2"></span>
        <span class="icon-bar b3"></span>
      </button>
      <a class="logo-link" href="<%= user_dashboard_path(current_user.uid) %>"><%= image_tag("logo.png", class:"logo-img") %></a>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        <li class="text-center">
          <a href="/<%= current_user.uid %>/artists" class=" menu-item icon" id="my-artists">
          <span class="glyphicon glyphicon-headphones" aria-hidden="true"></a>
        </li>
        <li class="text-center">
          <a href="/<%= current_user.uid %>/shows" class=" menu-item icon" id="my-shows">
          <span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span></a>
        </li>
        <li class="text-center">
          <a href="/logout" data-method="DELETE" class="menu-item icon">
          <span class="glyphicon glyphicon-log-out" aria-hidden="true"></span></a>
        </li>
        <li class="text-center"><%= link_to image_tag(current_user.image, class:"current-user-image"), user_dashboard_path(current_user.uid), class: "menu-item" %></li>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_spotify_login.html.erb
<div class="row">
  <%= link_to image_tag("spotify-login.png", id:"login-button"), :spotify_login, id: "login-button", class: "login-button" %>
</div>

app/views/shared/_welcome_spinner.html.erb
<div class="spinner" style="display:none">
  <div class="rect1"></div>
  <div class="rect2"></div>
  <div class="rect3"></div>
  <div class="rect4"></div>
  <div class="rect5"></div>
</div>